### ISSUE TITLE
Can you add \newlines ?

### ISSUE THREAD

**Issue by dataandcrowd** [mitchelloharawild/CV#1]
I wish I had some line spaces between award, scholarships, and competitions, however, \newlines doesn't seem to work here. Can you add that function into this package, or is there an alternative way?

**Comment by mitchelloharawild** [comment]
One way that you can add vertical spacing is using `\vspace{3em}`, where you can change `3em` to be the amount of vertical spacing you want.

**Comment by dataandcrowd** [comment]
> One way that you can add vertical spacing is using `\vspace{3em}`, where you can change `3em` to be the amount of vertical spacing you want.

Ahh, many thanks! Now my CV looks very much organised :-)
