### ISSUE TITLE
Issue with unicode-math-table

### ISSUE THREAD

**Issue by alapo** [mitchelloharawild/CV#2]
I have tried rendering your example. Can't get it to go. I get the following error

```
! Undefined control sequence.
l.931   \file_get:nnN
                      {unicode-math-table.tex} {} \l__um_mathtable_tl 
```
I think this may be related to loading `unicode-math` which can be seen [here](https://tex.stackexchange.com/questions/208988/prime-gives-undefined-control-sequence-in-xelatex-with-unicode-math)

Are you aware of anyone else having this issue?

**Comment by mitchelloharawild** [comment]
I haven't seen this issue, and I'm not sure why it is happening.
Perhaps try removing parts of the CV until it works, isolating the section that causes the problem

**Comment by alapo** [comment]
Thanks I kept troubleshooting and I can't even get the default `vitae::awesomecv` to work so definitely not a problem with your file.  Tried reinstalling the package but nothing. It's only a problem with `awesomecv` the other templates (hyndman, twentyseconds, moderncv)  do seem to work for me. Thanks for your help though!

**Comment by mitchelloharawild** [comment]
Hmm, odd. I'll transfer this issue to the vitae repo. It should bring about a bit more exposure to the issue, and hopefully others will have ideas for fixes.

edit: looks like I can't transfer this? not sure why. I'll close the issue for now.

**Comment by yihui** [comment]
In case you or anyone is still struggling with this issue, please see https://github.com/rstudio/rmarkdown/issues/1733#issuecomment-582165621
