### ISSUE TITLE
Error code: Latex

### ISSUE THREAD

**Issue by pcj25** [mitchelloharawild/CV#4]
Hi Mitchell, thanks so much for sharing the 'vitae' package, its much appreciated and such a great idea.  I've been playing around with it but unfortunately can't get the RMarkdown to 'knit' correctly despite my best efforts at de-bugging, updating my version of R etc.  All the code 'runs' from the template but it won't knit.  The error message is:-

Error: LaTeX failed to compile ModernCV-format.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips.
In addition: Warning messages:
1: In RefManageR::as.BibEntry(.) :
  rownames of data.frame not meaningful for creating keys
2: In system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
  '"pdflatex"' not found
Execution halted

Any help much appreciated, as I'm still an 'R' beginner.

Pamela

**Comment by Jigme77** [comment]
I would install a complete texlive or protext.

**Comment by mitchelloharawild** [comment]
Closing as this repository is not a place for questions / help. You can ask questions on stackoverflow or the RStudio community.

As suggested above, you will need to install some form of LaTeX. You can follow the suggested installation of tinytex to make this work.
