### ISSUE TITLE
How to produce a pdf document?

### ISSUE THREAD

**Issue by muhammet-ozkaraca** [mitchelloharawild/CV#6]
Hi Mitchell,
Thanks for this terrifying package. I just have one issue in my mind that I could not find the answer on web about this. So, basically I want a pdf output instead a html after I prepare my Rmd file. In this regard, I prefer to use vitae::markdowncv template. After a bit search on the web, I found some information on how to change it to pdf like adding this 
output:
  vitae::markdowncv:
    theme: kjhealy
    latex_engine: pdflatex

but it just does not work. So is there anything that you can suggest to change something on the YAML so that I can have a pdf output?

**Comment by mitchelloharawild** [comment]
Terrifying package? :laughing: 
The markdowncv template is a html template. You might be able to produce a PDF by printing the webpage to PDF, but the vitae package doesn't have facilities to support this. I will try to improve the documentation to further distinguish between PDF and HTML output formats. (https://github.com/mitchelloharawild/vitae/issues/162)

**Comment by muhammet-ozkaraca** [comment]
I wanted to mean like it is very excellent to produce such a high quality cv templates :) Sorry for misunderstanding :) And thanks for your comment 👍

**Comment by mitchelloharawild** [comment]
Haha, not a problem. I think I understood that the word you were looking for is 'terrific' :+1: 
Have a great day!

**Comment by muhammet-ozkaraca** [comment]
Yes, sorry for misunderstanding 😆

**Comment by aaronpeikert** [comment]
You can automate this step with [`pagedown`](https://github.com/rstudio/pagedown):

    Rscript -e 'pagedown::chrome_print("yourcv.html")'
